import React from 'react';
import { AlertCircle, ShieldAlert } from 'lucide-react';

export default function PredictionResult({ result }) {
  if (!result) return null;

  const { predicted_severity, probabilities } = result;
  
  // Find probability of the predicted class
  const prob = probabilities[predicted_severity.toString()];
  const confidence = prob ? (prob * 100).toFixed(2) : "0.00";

  // Determine severity label and colors
  let label = "Unknown";
  let colorTheme = "bg-slate-50 border-slate-200 text-slate-800";
  let iconTheme = "text-slate-600 bg-slate-100";
  
  switch(predicted_severity) {
    case 1:
      label = "Minor";
      colorTheme = "bg-emerald-50 border-emerald-200 text-emerald-900";
      iconTheme = "text-emerald-600 bg-emerald-100";
      break;
    case 2:
      label = "Moderate";
      colorTheme = "bg-blue-50 border-blue-200 text-blue-900";
      iconTheme = "text-blue-600 bg-blue-100";
      break;
    case 3:
      label = "Severe";
      colorTheme = "bg-amber-50 border-amber-200 text-amber-900";
      iconTheme = "text-amber-600 bg-amber-100";
      break;
    case 4:
      label = "Critical";
      colorTheme = "bg-rose-50 border-rose-200 text-rose-900";
      iconTheme = "text-rose-600 bg-rose-100";
      break;
    default:
      label = `Severity ${predicted_severity}`;
  }

  return (
    <div className={`rounded-2xl shadow-sm border overflow-hidden text-center flex flex-col justify-center p-8 transition-all ${colorTheme}`}>
      <div className="flex justify-center items-center mb-6">
        <div className={`w-20 h-20 rounded-2xl flex items-center justify-center shadow-sm ${iconTheme}`}>
          <ShieldAlert className="w-10 h-10" />
        </div>
      </div>
      
      <h2 className="text-sm font-bold uppercase tracking-widest opacity-70 mb-1">Predicted Severity</h2>
      <div className="flex items-baseline justify-center space-x-2">
        <span className="text-6xl font-black tracking-tight">{predicted_severity}</span>
      </div>
      <h3 className="text-2xl font-bold mt-2 tracking-tight opacity-90">{label}</h3>
      
      <div className="mt-4 flex justify-center">
        <span className="inline-flex items-center px-4 py-1.5 rounded-full text-sm font-semibold bg-white/60 backdrop-blur-sm border border-white/40 shadow-sm">
          Confidence: <span className="ml-1.5 font-bold">{confidence}%</span>
        </span>
      </div>
      
      <div className="mt-8 mx-auto max-w-sm p-4 bg-white/40 backdrop-blur-md rounded-xl text-left border border-white/50">
        <h4 className="text-xs font-bold uppercase tracking-wider mb-2 opacity-80 text-center border-b border-black/10 pb-2">Severity Reference</h4>
        <ul className="text-xs space-y-1.5 opacity-90 font-medium">
          <li className="flex items-center justify-between"><span className="flex items-center"><span className="w-2 h-2 rounded-full bg-emerald-500 mr-2"></span>Severity 1</span> <span className="opacity-75">Lowest Severity</span></li>
          <li className="flex items-center justify-between"><span className="flex items-center"><span className="w-2 h-2 rounded-full bg-blue-500 mr-2"></span>Severity 2</span> <span className="opacity-75">Moderate Severity</span></li>
          <li className="flex items-center justify-between"><span className="flex items-center"><span className="w-2 h-2 rounded-full bg-amber-500 mr-2"></span>Severity 3</span> <span className="opacity-75">High Severity</span></li>
          <li className="flex items-center justify-between"><span className="flex items-center"><span className="w-2 h-2 rounded-full bg-rose-500 mr-2"></span>Severity 4</span> <span className="opacity-75">Highest Severity</span></li>
        </ul>
      </div>

      <div className="mt-4 mx-auto max-w-sm p-4 text-left">
        <p className="text-xs opacity-80 flex leading-relaxed">
          <AlertCircle className="w-4 h-4 mr-2.5 flex-shrink-0 mt-0.5" />
          <span>Prediction is generated by a machine-learning model for analytical purposes and should not be treated as a definitive assessment.</span>
        </p>
      </div>
    </div>
  );
}
